# Generated by Django 3.1 on 2020-08-29 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank='', max_length=150)),
                ('username', models.CharField(blank='', max_length=150)),
            ],
        ),
    ]
