# Generated by Django 3.1 on 2020-08-30 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200830_0956'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
