# Generated by Django 3.1 on 2020-09-01 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='county',
            field=models.CharField(default='', max_length=100),
        ),
    ]
